//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB.Frameworks.Resources
{


	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessLogicLayerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessLogicLayerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PB.Frameworks.Resources.BusinessLogicLayerResource", typeof(BusinessLogicLayerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string BLLBASE_NOT_STARTED {
            get {
                return ResourceManager.GetString("BLLBASE_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string BLLBASE_STARTED {
            get {
                return ResourceManager.GetString("BLLBASE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity of table &apos;{0}&apos; with ID {1} does not exist..
        /// </summary>
        public static string DB_ENTITY_NOT_EXIST {
            get {
                return ResourceManager.GetString("DB_ENTITY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DB_OPERATION_DELETE {
            get {
                return ResourceManager.GetString("DB_OPERATION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string DB_OPERATION_SELECT {
            get {
                return ResourceManager.GetString("DB_OPERATION_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string DB_OPERATION_UPDATE {
            get {
                return ResourceManager.GetString("DB_OPERATION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address or username is incorrect..
        /// </summary>
        public static string EMAIL_OR_USERNAME_INCORRECT {
            get {
                return ResourceManager.GetString("EMAIL_OR_USERNAME_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter value for ID. ID must be specified for database operation &apos;Delete&apos;..
        /// </summary>
        public static string ID_NOT_SPECIFIED_DELETE {
            get {
                return ResourceManager.GetString("ID_NOT_SPECIFIED_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varification code is invalid. Please try again. If you are still having this issue, please contract administrator..
        /// </summary>
        public static string INVALID_VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("INVALID_VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {1},&lt;br /&gt;&lt;br /&gt;Please reset your password by clicking &lt;a href=&apos;{2}&apos;&gt;this link&lt;/a&gt; within 24 hours.&lt;br /&gt;&lt;br /&gt;Yours sincerely,&lt;br /&gt;&lt;br /&gt;{0}&lt;br /&gt;&lt;br /&gt;&lt;small&gt;Please do not reply to this e-mail as we do not monitor this e-mail address. If this e-mail is not expected, please disregard and delete.&lt;/small&gt;.
        /// </summary>
        public static string PASSWORD_RESET_BODY {
            get {
                return ResourceManager.GetString("PASSWORD_RESET_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Reset Your Password.
        /// </summary>
        public static string PASSWORD_RESET_SUBJECT {
            get {
                return ResourceManager.GetString("PASSWORD_RESET_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Welcome to {0}, {1}!&lt;/h3&gt;&lt;br /&gt;&lt;br /&gt;Please activate your account by clicking &lt;a href=&apos;{2}&apos;&gt;this link&lt;/a&gt; within 24 hours.&lt;br /&gt;&lt;br /&gt;Yours sincerely,&lt;br /&gt;&lt;br /&gt;{0}&lt;br /&gt;&lt;br /&gt;&lt;small&gt;Please do not reply to this e-mail as we do not monitor this e-mail address. If this e-mail is not expected, please disregard and delete.&lt;/small&gt;.
        /// </summary>
        public static string REGISTER_BODY {
            get {
                return ResourceManager.GetString("REGISTER_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Activate Your Account.
        /// </summary>
        public static string REGISTER_SUBJECT {
            get {
                return ResourceManager.GetString("REGISTER_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session key is invalid..
        /// </summary>
        public static string SESSION_KEY_INVALID {
            get {
                return ResourceManager.GetString("SESSION_KEY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not supported for database operation &apos;{1}&apos;..
        /// </summary>
        public static string TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; or email address &apos;{1}&apos; is already taken..
        /// </summary>
        public static string USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/e-mail or password is incorrect..
        /// </summary>
        public static string USERNAME_OR_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("USERNAME_OR_PASSWORD_INCORRECT", resourceCulture);
            }
        }
    }
}
