//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB.Frameworks.Resources
{


	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAccessLayerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAccessLayerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PB.Frameworks.Resources.DataAccessLayerResource", typeof(DataAccessLayerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database time stamp does not match with given time stamp. Possibly another user has modified database entity. Table name is &apos;{0}&apos;, ID is {1}, time stamp in database is {2}, and given time stamp is {3}..
        /// </summary>
        public static string DATE_MODIFIED_NOT_MATCH {
            get {
                return ResourceManager.GetString("DATE_MODIFIED_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given database entity did not have ID during database operation &apos;{0}&apos;..
        /// </summary>
        public static string DB_ENTITY_MUST_HAVE_ID {
            get {
                return ResourceManager.GetString("DB_ENTITY_MUST_HAVE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity of table &apos;{0}&apos; with ID {1} does not exist..
        /// </summary>
        public static string DB_ENTITY_NOT_EXIST {
            get {
                return ResourceManager.GetString("DB_ENTITY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DB_OPERATION_DELETE {
            get {
                return ResourceManager.GetString("DB_OPERATION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string DB_OPERATION_SELECT {
            get {
                return ResourceManager.GetString("DB_OPERATION_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string DB_OPERATION_UPDATE {
            get {
                return ResourceManager.GetString("DB_OPERATION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter value for ID. ID must be specified for database operation &apos;Delete&apos;..
        /// </summary>
        public static string ID_NOT_SPECIFIED_DELETE {
            get {
                return ResourceManager.GetString("ID_NOT_SPECIFIED_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not supported for database operation &apos;{1}&apos;..
        /// </summary>
        public static string TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
    }
}
